// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB22Z2oxQ4aV0feokQxxYRlt99j-9Z_emo',
    appId: '1:954124636072:web:71739800aa547882bf179d',
    messagingSenderId: '954124636072',
    projectId: 'coder-chat-4fc20',
    authDomain: 'coder-chat-4fc20.firebaseapp.com',
    databaseURL: 'https://coder-chat-4fc20-default-rtdb.firebaseio.com',
    storageBucket: 'coder-chat-4fc20.appspot.com',
    measurementId: 'G-DH932HR5DH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_1MHOrjnrNngdXm1uxhJA61qoBX0tRNI',
    appId: '1:954124636072:android:46c1b3a3f20ea3e5bf179d',
    messagingSenderId: '954124636072',
    projectId: 'coder-chat-4fc20',
    databaseURL: 'https://coder-chat-4fc20-default-rtdb.firebaseio.com',
    storageBucket: 'gs://coder-chat-4fc20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKVr-hFZHzMvY6OST99drS-DzkSdHhPwA',
    appId: '1:954124636072:ios:95d157a96896f3e8bf179d',
    messagingSenderId: '954124636072',
    projectId: 'coder-chat-4fc20',
    databaseURL: 'https://coder-chat-4fc20-default-rtdb.firebaseio.com',
    storageBucket: 'coder-chat-4fc20.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKVr-hFZHzMvY6OST99drS-DzkSdHhPwA',
    appId: '1:954124636072:ios:95d157a96896f3e8bf179d',
    messagingSenderId: '954124636072',
    projectId: 'coder-chat-4fc20',
    databaseURL: 'https://coder-chat-4fc20-default-rtdb.firebaseio.com',
    storageBucket: 'coder-chat-4fc20.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB22Z2oxQ4aV0feokQxxYRlt99j-9Z_emo',
    appId: '1:954124636072:web:6726b1f5b05fffe3bf179d',
    messagingSenderId: '954124636072',
    projectId: 'coder-chat-4fc20',
    authDomain: 'coder-chat-4fc20.firebaseapp.com',
    databaseURL: 'https://coder-chat-4fc20-default-rtdb.firebaseio.com',
    storageBucket: 'coder-chat-4fc20.appspot.com',
    measurementId: 'G-LC3N7Y42GT',
  );
}
